name: Minify dist
on: [push]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          package-manager-cache: false
      - run: npm install
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v7

